# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: krehak
open_collective: krehak
ko_fi: krehak
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: krehak
issuehunt: krehak
otechie: krehak
custom: ['https://www.paypal.com/donate?hosted_button_id=N3PCMDLKXCS6N']
